# New line before prompt
add_newline = true

# [character]
# success_symbol = "[❯](bold green) "
# error_symbol = "[❯](bold red) "
# vicmd_symbol = "[❮](bold green) "

[directory]
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false

[container]
disabled = true
